import type { Metadata } from "next";
import { LegalPage } from "../_components/legal-page";

export const metadata: Metadata = {
  title: "Privacy Policy — Custodia",
  description:
    "How Custodia collects, uses, and protects data on custodia-privacy.com. Generated by Custodia's own policy agent from a real scan of our site.",
};

export default function PrivacyPolicyPage() {
  return (
    <LegalPage
      fileBasename="privacy"
      title="Privacy Policy"
      generatedNote="This policy was generated by Custodia's own Policy Agent using scan findings from custodia-privacy.com. We dogfood the product on ourselves."
    />
  );
}
