/**
 * Shared types used across the application.
 * Database types are generated by Prisma — these are for UI/API contracts.
 */

/** Compliance regulation identifiers */
export type Regulation = "gdpr" | "ccpa" | "cpra" | "vcdpa" | "ctdpa" | "cpa" | "ucpa";

/** Compliance score per regulation */
export interface ComplianceScores {
  overall: number;
  regulations: Record<Regulation, number | null>;
}

/** Quick scan result (public, lead-gen) */
export interface QuickScanResult {
  scanId: string;
  url: string;
  cookiesFound: number;
  trackersFound: number;
  issuesFound: number;
  topFindings: QuickFinding[];
  score: number;
}

export interface QuickFinding {
  title: string;
  severity: "critical" | "warning" | "info";
  description: string;
}

/** Banner embed script config (served to customer sites) */
export interface BannerPublicConfig {
  siteId: string;
  position: "bottom" | "bottom-left" | "bottom-right" | "center";
  theme: "light" | "dark" | "auto";
  primaryColor: string;
  showLogo: boolean;
  customCss: string;
  content: {
    title: string;
    description: string;
    acceptAllText: string;
    rejectAllText: string;
    customizeText: string;
    privacyPolicyUrl: string;
  };
  categories: {
    key: string;
    name: string;
    description: string;
    required: boolean;
  }[];
  regulations: {
    gdpr?: { enabled: boolean; mode: "opt-in" };
    ccpa?: { enabled: boolean; mode: "opt-out" };
  };
}

/** Agent job payload for BullMQ */
export interface AgentJobPayload {
  runId: string;
  orgId: string;
  agentType: string;
  input: Record<string, unknown>;
}

/** Scan job payload for BullMQ */
export interface ScanJobPayload {
  scanId: string;
  siteId: string;
  domain: string;
  scanType: "full" | "quick" | "monitoring";
  maxPages: number;
}

/** Data inventory PII scan job (connector introspection + sampling + classify) */
export interface DataScanJobPayload {
  scanRunId: string;
  orgId: string;
  integrationId: string;
  provider: string;
}

/** Deletion executor job (DSAR or retention run) */
export interface DeletionJobPayload {
  runId: string;
  orgId: string;
}

/** Scanner result for a single page */
export interface PageScanResult {
  url: string;
  cookies: CookieInfo[];
  trackers: TrackerInfo[];
  scripts: ScriptInfo[];
  forms: FormInfo[];
}

export interface CookieInfo {
  name: string;
  domain: string;
  path: string;
  secure: boolean;
  httpOnly: boolean;
  sameSite: string;
  expires: string | null;
  category: "necessary" | "analytics" | "marketing" | "preferences" | "unknown";
  description: string | null;
  knownService: string | null;
}

export interface TrackerInfo {
  name: string;
  domain: string;
  category: "analytics" | "advertising" | "social" | "fingerprinting" | "other";
  description: string;
  regulations: Regulation[];
}

export interface ScriptInfo {
  src: string;
  isThirdParty: boolean;
  service: string | null;
  category: string | null;
}

export interface FormInfo {
  action: string;
  method: string;
  fields: { name: string; type: string; label: string | null }[];
  collectsPersonalData: boolean;
}
